Search.appendIndex(
    [
                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___construct"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Gives\u0020the\u0020first\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetSubType\u0028\u0029",
            "name": "getSubType",
            "summary": "Gives\u0020the\u0020second\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getSubType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetEssence\u0028\u0029",
            "name": "getEssence",
            "summary": "Gives\u0020the\u0020type\u0020and\u0020subtype\u0020of\u0020a\u0020media\u0020type.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getEssence"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetParameters\u0028\u0029",
            "name": "getParameters",
            "summary": "Gives\u0020an\u0020array\u0020of\u0020parameters\u0020of\u0020a\u0020media\u0020type,\nif\u0020any\u0020parameters\u0020exist.\u0020Otherwise,\u0020it\u0020will\u0020return\u0020an\u0020empty\u0020array.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getParameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetParameterValue\u0028\u0029",
            "name": "getParameterValue",
            "summary": "Gives\u0020the\u0020value\u0020of\u0020a\u0020specified\u0020parameter\u0020of\u0020a\u0020media\u0020type,\nif\u0020that\u0020parameter\u0020exists\u003B\u0020otherwise,\u0020it\u0020will\u0020return\u0020a\u0020null\u0020value.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getParameterValue"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___toString"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AserializeParameterValue\u0028\u0029",
            "name": "serializeParameterValue",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_serializeParameterValue"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_type"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024subType",
            "name": "subType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_subType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_parameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser",
            "name": "MediaTypeParser",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AparseOrNull\u0028\u0029",
            "name": "parseOrNull",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_parseOrNull"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectType\u0028\u0029",
            "name": "collectType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectSubType\u0028\u0029",
            "name": "collectSubType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectSubType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectParameters\u0028\u0029",
            "name": "collectParameters",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectParameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParserException",
            "name": "MediaTypeParserException",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParserException.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "namespaces/neoncitylights-mediatype.html"
        },                {
            "fqsen": "\\Neoncitylights",
            "name": "Neoncitylights",
            "summary": "",
            "url": "namespaces/neoncitylights.html"
        }            ]
);
