Search.appendIndex(
    [
                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___construct"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetEssence\u0028\u0029",
            "name": "getEssence",
            "summary": "Gives\u0020the\u0020type\u0020and\u0020subtype\u0020of\u0020a\u0020media\u0020type.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getEssence"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetParameterValue\u0028\u0029",
            "name": "getParameterValue",
            "summary": "Gives\u0020the\u0020value\u0020of\u0020a\u0020specified\u0020parameter\u0020of\u0020a\u0020media\u0020type,\nif\u0020that\u0020parameter\u0020exists\u003B\u0020otherwise,\u0020it\u0020will\u0020return\u0020a\u0020null\u0020value.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getParameterValue"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisImage\u0028\u0029",
            "name": "isImage",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isImage"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisAudioOrVideo\u0028\u0029",
            "name": "isAudioOrVideo",
            "summary": "https\u003A\/\/mimesniff.spec.whatwg.org\/\u0023audio\u002Dor\u002Dvideo\u002Dmime\u002Dtype",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isAudioOrVideo"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisFont\u0028\u0029",
            "name": "isFont",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isFont"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisZipBased\u0028\u0029",
            "name": "isZipBased",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isZipBased"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisArchive\u0028\u0029",
            "name": "isArchive",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isArchive"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisXml\u0028\u0029",
            "name": "isXml",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isXml"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisHtml\u0028\u0029",
            "name": "isHtml",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isHtml"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisScriptable\u0028\u0029",
            "name": "isScriptable",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isScriptable"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisJavaScript\u0028\u0029",
            "name": "isJavaScript",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isJavaScript"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AisJson\u0028\u0029",
            "name": "isJson",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_isJson"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003Aminimize\u0028\u0029",
            "name": "minimize",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_minimize"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___toString"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AserializeParameterValue\u0028\u0029",
            "name": "serializeParameterValue",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_serializeParameterValue"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024type",
            "name": "type",
            "summary": "Gives\u0020the\u0020first\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_type"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024subType",
            "name": "subType",
            "summary": "Gives\u0020the\u0020second\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_subType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "Gives\u0020an\u0020array\u0020of\u0020parameters\u0020of\u0020a\u0020media\u0020type,\nif\u0020any\u0020parameters\u0020exist.\u0020Otherwise,\u0020it\u0020will\u0020return\u0020an\u0020empty\u0020array.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_parameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser",
            "name": "MediaTypeParser",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AparseOrNull\u0028\u0029",
            "name": "parseOrNull",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_parseOrNull"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectType\u0028\u0029",
            "name": "collectType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectSubType\u0028\u0029",
            "name": "collectSubType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectSubType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParser\u003A\u003AcollectParameters\u0028\u0029",
            "name": "collectParameters",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParser.html#method_collectParameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaTypeParserException",
            "name": "MediaTypeParserException",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaTypeParserException.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "namespaces/neoncitylights-mediatype.html"
        },                {
            "fqsen": "\\Neoncitylights",
            "name": "Neoncitylights",
            "summary": "",
            "url": "namespaces/neoncitylights.html"
        }            ]
);
