Search.appendIndex(
    [
                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___construct"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AnewFromString\u0028\u0029",
            "name": "newFromString",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_newFromString"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Gives\u0020the\u0020first\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetSubType\u0028\u0029",
            "name": "getSubType",
            "summary": "Gives\u0020the\u0020second\u0020portion\u0020of\u0020a\u0020media\u0020type\u0027s\u0020essence.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getSubType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetEssence\u0028\u0029",
            "name": "getEssence",
            "summary": "Gives\u0020the\u0020type\u0020and\u0020subtype\u0020of\u0020a\u0020media\u0020type.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getEssence"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetParameters\u0028\u0029",
            "name": "getParameters",
            "summary": "Gives\u0020an\u0020array\u0020of\u0020parameters\u0020of\u0020a\u0020media\u0020type,\nif\u0020any\u0020parameters\u0020exist.\u0020Otherwise,\u0020it\u0020will\u0020return\u0020an\u0020empty\u0020array.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getParameters"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003AgetParameterValue\u0028\u0029",
            "name": "getParameterValue",
            "summary": "Gives\u0020the\u0020value\u0020of\u0020a\u0020specified\u0020parameter\u0020of\u0020a\u0020media\u0020type,\nif\u0020that\u0020parameter\u0020exists\u003B\u0020otherwise,\u0020it\u0020will\u0020return\u0020a\u0020null\u0020value.",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method_getParameterValue"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#method___toString"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003ATOKEN_TYPE_SEPARATOR",
            "name": "TOKEN_TYPE_SEPARATOR",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#constant_TOKEN_TYPE_SEPARATOR"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003ATOKEN_DELIMETER",
            "name": "TOKEN_DELIMETER",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#constant_TOKEN_DELIMETER"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003ATOKEN_EQUAL",
            "name": "TOKEN_EQUAL",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#constant_TOKEN_EQUAL"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_type"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024subType",
            "name": "subType",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_subType"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType\\MediaType\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "",
            "url": "classes/Neoncitylights-MediaType-MediaType.html#property_parameters"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Neoncitylights\\MediaType",
            "name": "MediaType",
            "summary": "",
            "url": "namespaces/neoncitylights-mediatype.html"
        },                {
            "fqsen": "\\Neoncitylights",
            "name": "Neoncitylights",
            "summary": "",
            "url": "namespaces/neoncitylights.html"
        }            ]
);
